# Generated by Django 5.0.3 on 2025-05-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='data/')),
                ('code', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('PR', 'Proteins'), ('VI', 'Vitamins'), ('CR', 'Creatines'), ('AA', 'Aminoacids'), ('PW', 'Pre-Workout')], max_length=100)),
            ],
        ),
    ]
