# Generated by Django 5.0.3 on 2025-05-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='description',
            field=models.TextField(default='Описот не е достапен'),
        ),
    ]
