# Generated by Django 5.0.3 on 2025-05-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_supplement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='category',
            field=models.CharField(choices=[('protein', 'Proteins'), ('vitamins', 'Vitamins'), ('creatine', 'Creatines'), ('aminoacids', 'Aminoacids'), ('preworkout', 'Pre-Workout')], max_length=100),
        ),
    ]
